create table countries_population ( name varchar2(50), continent varchar2(30), population int );
truncate table COUNTRIES_POPULATION;
begin 
insert into countries_population values ('Afghanistan',initcap('ASIA'),27101365); 
insert into countries_population values ('Albania',initcap('EUROPE'),2893005); 
insert into countries_population values ('Algeria',initcap('AFRICA'),40400000); 
insert into countries_population values ('Andorra',initcap('EUROPE'),76949); 
insert into countries_population values ('Angola',initcap('AFRICA'),24383301); 
insert into countries_population values ('Antigua and Barbuda',initcap('NORTH AMERICA'),86295); 
insert into countries_population values ('Argentina',initcap('SOUTH AMERICA'),43590400); 
insert into countries_population values ('Armenia',initcap('EUROPE'),3004000); 
insert into countries_population values ('Australia',initcap('OCEANIA'),24016400); 
insert into countries_population values ('Austria',initcap('EUROPE'),8662588); 
insert into countries_population values ('Azerbaijan',initcap('EUROPE'),9687300); 
insert into countries_population values ('Bahamas',initcap('NORTH AMERICA'),393000); 
insert into countries_population values ('Bahrain',initcap('ASIA'),1404900); 
insert into countries_population values ('Bangladesh',initcap('ASIA'),159663000); 
insert into countries_population values ('Barbados',initcap('NORTH AMERICA'),285000); 
insert into countries_population values ('Belarus',initcap('EUROPE'),9494200); 
insert into countries_population values ('Belgium',initcap('EUROPE'),11291746); 
insert into countries_population values ('Belize',initcap('NORTH AMERICA'),368310); 
insert into countries_population values ('Benin',initcap('AFRICA'),10653654); 
insert into countries_population values ('Bhutan',initcap('ASIA'),768960); 
insert into countries_population values ('Bolivia',initcap('SOUTH AMERICA'),10985059); 
insert into countries_population values ('Bosnia and Herzegovina',initcap('EUROPE'),3791622); 
insert into countries_population values ('Botswana',initcap('AFRICA'),2141206); 
insert into countries_population values ('Brazil',initcap('SOUTH AMERICA'),205444000); 
insert into countries_population values ('Brunei',initcap('ASIA'),411900); 
insert into countries_population values ('Bulgaria',initcap('EUROPE'),7202198); 
insert into countries_population values ('Burkina',initcap('AFRICA'),18450494); 
insert into countries_population values ('Burundi',initcap('AFRICA'),10114505); 
insert into countries_population values ('Cambodia',initcap('ASIA'),15626444); 
insert into countries_population values ('Cameroon',initcap('AFRICA'),23924000); 
insert into countries_population values ('Canada',initcap('NORTH AMERICA'),35985751); 
insert into countries_population values ('Cape Verde',initcap('AFRICA'),531239); 
insert into countries_population values ('Central African Republic',initcap('AFRICA'),4998000); 
insert into countries_population values ('Chad',initcap('AFRICA'),14497000); 
insert into countries_population values ('Chile',initcap('SOUTH AMERICA'),18191900); 
insert into countries_population values ('China',initcap('ASIA'),1374150000); 
insert into countries_population values ('Colombia',initcap('SOUTH AMERICA'),48470000); 
insert into countries_population values ('Comoros',initcap('AFRICA'),806153); 
insert into countries_population values ('Congo',initcap('AFRICA'),85026000); 
insert into countries_population values ('Costa Rica',initcap('NORTH AMERICA'),4832234); 
insert into countries_population values ('Croatia',initcap('EUROPE'),4225316); 
insert into countries_population values ('Cuba',initcap('NORTH AMERICA'),11238317); 
insert into countries_population values ('Cyprus',initcap('EUROPE'),847000); 
insert into countries_population values ('Czech Republic',initcap('EUROPE'),10541466); 
insert into countries_population values ('Denmark',initcap('EUROPE'),5699220); 
insert into countries_population values ('Djibouti',initcap('AFRICA'),900000); 
insert into countries_population values ('Dominica',initcap('NORTH AMERICA'),71293); 
insert into countries_population values ('Dominican Republic',initcap('NORTH AMERICA'),10075045); 
insert into countries_population values ('East Timor',initcap('ASIA'),1167242); 
insert into countries_population values ('Ecuador',initcap('SOUTH AMERICA'),16278844); 
insert into countries_population values ('Egypt',initcap('AFRICA'),90174100); 
insert into countries_population values ('El Salvador',initcap('NORTH AMERICA'),6520675); 
insert into countries_population values ('Equatorial Guinea',initcap('AFRICA'),1222442); 
insert into countries_population values ('Eritrea',initcap('AFRICA'),5352000); 
insert into countries_population values ('Estonia',initcap('EUROPE'),1313271); 
insert into countries_population values ('Ethiopia',initcap('AFRICA'),92206000); 
insert into countries_population values ('Fiji',initcap('OCEANIA'),867000); 
insert into countries_population values ('Finland',initcap('EUROPE'),5496275); 
insert into countries_population values ('France',initcap('EUROPE'),66539000); 
insert into countries_population values ('Gabon',initcap('AFRICA'),1802278); 
insert into countries_population values ('Georgia',initcap('EUROPE'),3729500); 
insert into countries_population values ('Germany',initcap('EUROPE'),81292400); 
insert into countries_population values ('Ghana',initcap('AFRICA'),27043093); 
insert into countries_population values ('Greece',initcap('EUROPE'),10846979); 
insert into countries_population values ('Grenada',initcap('NORTH AMERICA'),103328); 
insert into countries_population values ('Guatemala',initcap('NORTH AMERICA'),16176133); 
insert into countries_population values ('Guinea',initcap('AFRICA'),12947000); 
insert into countries_population values ('Guinea-Bissau',initcap('AFRICA'),1547777); 
insert into countries_population values ('Guyana',initcap('SOUTH AMERICA'),746900); 
insert into countries_population values ('Haiti',initcap('NORTH AMERICA'),11078033); 
insert into countries_population values ('Honduras',initcap('NORTH AMERICA'),8576532); 
insert into countries_population values ('Hungary',initcap('EUROPE'),9849000); 
insert into countries_population values ('Iceland',initcap('EUROPE'),331310); 
insert into countries_population values ('India',initcap('ASIA'),1282600000); 
insert into countries_population values ('Indonesia',initcap('ASIA'),258705000); 
insert into countries_population values ('Iran',initcap('ASIA'),78916000); 
insert into countries_population values ('Iraq',initcap('ASIA'),36575000); 
insert into countries_population values ('Ireland',initcap('EUROPE'),4635400); 
insert into countries_population values ('Israel',initcap('ASIA'),8462000); 
insert into countries_population values ('Italy',initcap('EUROPE'),60685487); 
insert into countries_population values ('Ivory Coast',initcap('AFRICA'),22671331); 
insert into countries_population values ('Jamaica',initcap('NORTH AMERICA'),2723246); 
insert into countries_population values ('Japan',initcap('ASIA'),126880000); 
insert into countries_population values ('Jordan',initcap('ASIA'),7748000); 
insert into countries_population values ('Kazakhstan',initcap('ASIA'),17630700); 
insert into countries_population values ('Kenya',initcap('AFRICA'),47251000); 
insert into countries_population values ('Kiribati',initcap('OCEANIA'),113400); 
insert into countries_population values ('Korea, North',initcap('ASIA'),25281000); 
insert into countries_population values ('Korea, South',initcap('ASIA'),51529338); 
insert into countries_population values ('Kyrgyzstan',initcap('ASIA'),5975000); 
insert into countries_population values ('Laos',initcap('ASIA'),6472400); 
insert into countries_population values ('Latvia',initcap('EUROPE'),1973700); 
insert into countries_population values ('Lebanon',initcap('ASIA'),4168000); 
insert into countries_population values ('Lesotho',initcap('AFRICA'),1894194); 
insert into countries_population values ('Liberia',initcap('AFRICA'),4615000); 
insert into countries_population values ('Libya',initcap('AFRICA'),6330000); 
insert into countries_population values ('Liechtenstein',initcap('EUROPE'),37370); 
insert into countries_population values ('Lithuania',initcap('EUROPE'),2890679); 
insert into countries_population values ('Luxembourg',initcap('EUROPE'),562958); 
insert into countries_population values ('Macedonia',initcap('EUROPE'),2069172); 
insert into countries_population values ('Madagascar',initcap('AFRICA'),22434363); 
insert into countries_population values ('Malawi',initcap('AFRICA'),16832910); 
insert into countries_population values ('Malaysia',initcap('ASIA'),30819500); 
insert into countries_population values ('Maldives',initcap('ASIA'),341256); 
insert into countries_population values ('Mali',initcap('AFRICA'),18135000); 
insert into countries_population values ('Malta',initcap('EUROPE'),445426); 
insert into countries_population values ('Marshall Islands',initcap('OCEANIA'),54880);  
insert into countries_population values ('Mauritania',initcap('AFRICA'),3718678); 
insert into countries_population values ('Mauritius',initcap('AFRICA'),1262879); 
insert into countries_population values ('Mexico',initcap('NORTH AMERICA'),122273500); 
insert into countries_population values ('Moldova',initcap('EUROPE'),3555200); 
insert into countries_population values ('Monaco',initcap('EUROPE'),37800); 
insert into countries_population values ('Mongolia',initcap('ASIA'),3059684); 
insert into countries_population values ('Montenegro',initcap('EUROPE'),621810); 
insert into countries_population values ('Morocco',initcap('AFRICA'),33337529); 
insert into countries_population values ('Mozambique',initcap('AFRICA'),26423700); 
insert into countries_population values ('Myanmar',initcap('ASIA'),54363000); 
insert into countries_population values ('Namibia',initcap('AFRICA'),2324400); 
insert into countries_population values ('Nauru',initcap('OCEANIA'),10084); 
insert into countries_population values ('Nepal',initcap('ASIA'),28431500); 
insert into countries_population values ('Netherlands',initcap('EUROPE'),16981400); 
insert into countries_population values ('New Zealand',initcap('OCEANIA'),4645120); 
insert into countries_population values ('Nicaragua',initcap('NORTH AMERICA'),6198154); 
insert into countries_population values ('Niger',initcap('AFRICA'),20715000); 
insert into countries_population values ('Nigeria',initcap('AFRICA'),186988000); 
insert into countries_population values ('Norway',initcap('EUROPE'),5214890); 
insert into countries_population values ('Oman',initcap('ASIA'),4319745); 
insert into countries_population values ('Pakistan',initcap('ASIA'),192420472); 
insert into countries_population values ('Palau',initcap('OCEANIA'),17950); 
insert into countries_population values ('Panama',initcap('NORTH AMERICA'),3764166); 
insert into countries_population values ('Papua New Guinea',initcap('OCEANIA'),8083700); 
insert into countries_population values ('Paraguay',initcap('SOUTH AMERICA'),7112594); 
insert into countries_population values ('Peru',initcap('SOUTH AMERICA'),31488700); 
insert into countries_population values ('Philippines',initcap('ASIA'),102612900); 
insert into countries_population values ('Poland',initcap('EUROPE'),38484000); 
insert into countries_population values ('Portugal',initcap('EUROPE'),10374822); 
insert into countries_population values ('Qatar',initcap('ASIA'),2463460); 
insert into countries_population values ('Romania',initcap('EUROPE'),19942642); 
insert into countries_population values ('Russia',initcap('ASIA'),146491330); 
insert into countries_population values ('Rwanda',initcap('AFRICA'),11553188); 
insert into countries_population values ('Saint Kitts and Nevis',initcap('NORTH AMERICA'),46204); 
insert into countries_population values ('Saint Lucia',initcap('NORTH AMERICA'),186000); 
insert into countries_population values ('Saint Vincent and the Grenadines',initcap('NORTH AMERICA'),109991); 
insert into countries_population values ('Samoa',initcap('OCEANIA'),187820); 
insert into countries_population values ('San Marino',initcap('EUROPE'),32968); 
insert into countries_population values ('Sao Tome and Principe',initcap('AFRICA'),187356); 
insert into countries_population values ('Saudi Arabia',initcap('ASIA'),32248200); 
insert into countries_population values ('Senegal',initcap('AFRICA'),14354690); 
insert into countries_population values ('Serbia',initcap('EUROPE'),7114393); 
insert into countries_population values ('Seychelles',initcap('AFRICA'),91400); 
insert into countries_population values ('Sierra Leone',initcap('AFRICA'),6592000); 
insert into countries_population values ('Singapore',initcap('ASIA'),5535000); 
insert into countries_population values ('Slovakia',initcap('EUROPE'),5424058); 
insert into countries_population values ('Slovenia',initcap('EUROPE'),2069223); 
insert into countries_population values ('Solomon Islands',initcap('OCEANIA'),642000); 
insert into countries_population values ('Somalia',initcap('AFRICA'),11079000); 
insert into countries_population values ('South Africa',initcap('AFRICA'),54956900); 
insert into countries_population values ('South Sudan',initcap('AFRICA'),11892934); 
insert into countries_population values ('Spain',initcap('EUROPE'),46423064); 
insert into countries_population values ('Sri Lanka',initcap('ASIA'),20966000); 
insert into countries_population values ('Sudan',initcap('AFRICA'),39598700); 
insert into countries_population values ('Suriname',initcap('SOUTH AMERICA'),534189); 
insert into countries_population values ('Swaziland',initcap('AFRICA'),1132657); 
insert into countries_population values ('Sweden',initcap('EUROPE'),9838480); 
insert into countries_population values ('Switzerland',initcap('EUROPE'),8306200); 
insert into countries_population values ('Syria',initcap('ASIA'),23558929); 
insert into countries_population values ('Tajikistan',initcap('ASIA'),8352000); 
insert into countries_population values ('Tanzania',initcap('AFRICA'),55155000); 
insert into countries_population values ('Thailand',initcap('ASIA'),65218156); 
insert into countries_population values ('Togo',initcap('AFRICA'),7143000); 
insert into countries_population values ('Tonga',initcap('OCEANIA'),103252); 
insert into countries_population values ('Trinidad and Tobago',initcap('NORTH AMERICA'),1349667); 
insert into countries_population values ('Tunisia',initcap('AFRICA'),10982754); 
insert into countries_population values ('Turkey',initcap('ASIA'),77695904); 
insert into countries_population values ('Turkmenistan',initcap('ASIA'),4751120); 
insert into countries_population values ('Tuvalu',initcap('OCEANIA'),10640); 
insert into countries_population values ('Uganda',initcap('AFRICA'),34856813); 
insert into countries_population values ('Ukraine',initcap('EUROPE'),42789472); 
insert into countries_population values ('United Arab Emirates',initcap('ASIA'),9267000); 
insert into countries_population values ('United Kingdom',initcap('EUROPE'),64800000); 
insert into countries_population values ('United States',initcap('NORTH AMERICA'),322586000); 
insert into countries_population values ('Uruguay',initcap('SOUTH AMERICA'),3480222); 
insert into countries_population values ('Uzbekistan',initcap('ASIA'),31022500); 
insert into countries_population values ('Vanuatu',initcap('OCEANIA'),277500); 
insert into countries_population values ('Vatican City',initcap('EUROPE'),839); 
insert into countries_population values ('Venezuela',initcap('SOUTH AMERICA'),31028700); 
insert into countries_population values ('Vietnam',initcap('ASIA'),91700000); 
insert into countries_population values ('Yemen',initcap('ASIA'),25956000); 
insert into countries_population values ('Zambia',initcap('AFRICA'),15933883); 
insert into countries_population values ('Zimbabwe',initcap('AFRICA'),15967000); 
 
commit; 
end;



select c.*, 
         row_number() over (  
             partition by continent 
             order by population desc) as pop_rank 
  from   COUNTRIES_POPULATION c;